AAD Usage Clarifications
cose-wg/HPKE pull request #51
Opened 2024-02-11 15:11 UTC by hannestschofenig

Based on interop testing with Daisuke

2024-02-11 19:58 UTC, laurencelundblade requested changes
- Agree with use of the "aad" parameter.
- A few comments and typos
- Lament about the info param / structure

2024-02-11 19:58 UTC, laurencelundblade commented on draft-ietf-cose-hpke.md
> +discouraged by RFC 9052, this profile RECOMMENDS the use of the 'kid' parameter
COSE-HKPE is not really a "profile". It is a new standard encryption mechanism for COSE (not a big deal, but I thought I'd mention it).

2024-02-11 19:58 UTC, laurencelundblade commented on draft-ietf-cose-hpke.md
> +(or other parameters) to explicitly identify the static recipient public key
I think the use or non-use of kid depends on the use case. If you have a use case where the key is known already then it is not needed (not a big deal, but I thought I'd mention it).

2024-02-11 19:58 UTC, laurencelundblade commented on draft-ietf-cose-hpke.md
> +encrypted with the CEK. This ciphertext may be detached, and if not detached, then
I don't think detached / non-detached needs to be mention in this document. (not a big deal, but I thought I'd mention it).

2024-02-11 19:58 UTC, laurencelundblade commented on draft-ietf-cose-hpke.md
> +At layer 1 where HPKE is used to encrypted the CEK, the "aad" parameter
"encrypt", not "encrypted"

2024-02-11 19:58 UTC, laurencelundblade commented on draft-ietf-cose-hpke.md
> +Section 5.3 of {{RFC9052}} need to be followed, which includes the
"need" -> "MUST"

2024-02-11 19:58 UTC, laurencelundblade commented on draft-ietf-cose-hpke.md
> +When encrypting the content at layer 0 then the instructions in
This seems correct to me.

2024-02-11 19:58 UTC, laurencelundblade commented on draft-ietf-cose-hpke.md
> +At layer 1 where HPKE is used to encrypted the CEK, the "aad" parameter
This is progress on #42. It is saying what the "aad" parameter input to the Seal() API is.

2024-02-11 19:58 UTC, laurencelundblade commented on draft-ietf-cose-hpke.md
> +Data described in Section 4.3 and Section 5.3 in RFC 9052. If this field is
This is restating some of 9052. I kind of thought it's better not to do restatements and if you do, say the original is normative. (not a big deal, but I thought I'd mention it).

2024-02-11 19:58 UTC, laurencelundblade commented on draft-ietf-cose-hpke.md
> +provided in {{info}}.
Wish we could improve this a lot. Kind of seems like the user of COSE-HPKE has to do a deep threat analysis of their use case to know what to do here. Probably they have to do a lot less than in regular COSE, because COSE-HPKE internally takes care of a lot of this.

2024-02-11 19:59 UTC, OR13 approved these changes

2024-02-11 20:52 UTC, dajiaji commented on draft-ietf-cose-hpke.md
> +Data described in Section 4.3 and Section 5.3 in RFC 9052. If this field is
I agree with Laurence that there is no need to restate what is written in another spec. However, I also think that this PR should be merged once and editorial corrections can be done later as a PR that resolves the issue (#41) Laurence filed.

2024-02-11 21:02 UTC, dajiaji commented on draft-ietf-cose-hpke.md
> +provided in {{info}}.
I agree, and I think it would be better to solve this with another PR.

2024-02-12 09:27 UTC, hannestschofenig commented on draft-ietf-cose-hpke.md
> +discouraged by RFC 9052, this profile RECOMMENDS the use of the 'kid' parameter
```suggestion
discouraged by RFC 9052, this documents RECOMMENDS the use of the 'kid' parameter
```

2024-02-12 09:32 UTC, hannestschofenig commented on draft-ietf-cose-hpke.md
> +Section 5.3 of {{RFC9052}} need to be followed, which includes the
```suggestion
Section 5.3 of {{RFC9052}} MUST to be followed, which includes the
```

2024-02-12 09:35 UTC, hannestschofenig commented on draft-ietf-cose-hpke.md
> +(or other parameters) to explicitly identify the static recipient public key
That's correct. You don't have to use it but we recommend it in the generic case.

2024-02-12 09:37 UTC, hannestschofenig commented on draft-ietf-cose-hpke.md
> +encrypted with the CEK. This ciphertext may be detached, and if not detached, then
I downgraded the sentence to avoid the use of the MAY to may

2024-02-12 09:39 UTC, hannestschofenig commented on draft-ietf-cose-hpke.md
> +At layer 1 where HPKE is used to encrypted the CEK, the "aad" parameter
```suggestion
At layer 1 where HPKE is used to encrypt the CEK, the "aad" parameter
```

2024-02-12 09:45 UTC, hannestschofenig commented on draft-ietf-cose-hpke.md
> +The external_aad field in the Enc_structure contains the Externally Supplied
```suggestion
```

2024-02-12 09:45 UTC, hannestschofenig commented on draft-ietf-cose-hpke.md
> +Data described in Section 4.3 and Section 5.3 in RFC 9052. If this field is
```suggestion
```

2024-02-12 09:45 UTC, hannestschofenig commented on draft-ietf-cose-hpke.md
> +not supplied, it defaults to a zero-length byte string.
```suggestion
```

2024-02-14 10:23 UTC, merged